### ISSUE TITLE
Cannot input characters with dead keys

### ISSUE THREAD

**Issue by manuel-rhdt** [jwilm/alacritty#1041]
Which operating system does the issue occur on?
MacOS 10.13.2

I cannot input characters requiring dead keys (e.g. with US International layout ñ or é or even " ). After pressing the dead key nothing happens. The next character is just printed normal.

**Comment by gullevek** [comment]
Can confirm this on macOS 10.12.6 too

**Comment by EVODelavega** [comment]
I don't think this is OS related (FYI confirmed for OSX 10.13.3), I'll try on fedora later on. I suspect it's an issue there, too. I'll confirm after testing

**Comment by EVODelavega** [comment]
Oh forgot about this: confirmed on fedora 27, too (wayland, nouveau)

**Comment by salazar** [comment]
Facing this on macOS 10.13.4 - ref 1b7ffea. Available to provide more info if needed.

**Comment by adrigzr** [comment]
Same here. Any news on this one? Thanks!

**Comment by francesca64** [comment]
@adrigzr yes.

I encourage anyone interested to try out  https://github.com/francesca64/alacritty/tree/macos-kb. Relevant winit PR: tomaka/winit#518

**Comment by adrigzr** [comment]
Thank you @francesca64, this is working for me.

To add more, its working the dead-key compose thing and the `option+e+e` combination. The later is not showing the yellow prefix when you type `option+e`, but at least is usable now.

**Comment by salazar** [comment]
Thank you @francesca64; just tried out your branch and it works for the cases I've tested so far.

**Comment by chrisduerr** [comment]
I was thinking about the best way to handle all the different issues that are solved by this, so we could close them all when they're done.

Then I saw you've compiled a list with all issues in tomaka/winit#518 @francesca64. That's just amazing!

**Comment by francesca64** [comment]
@chrisduerr ah, thanks. I did that to make my PR look cooler.

I'll probably merge the PR tonight, and I want to cut another winit release in the next day or so.

**Comment by francesca64** [comment]
@EVODelavega you're not wrong, but did you try the branch anyway? I'd be quite surprised if that weren't fixed by tomaka/winit#451.

**Comment by EVODelavega** [comment]
@francesca64  Haven't tried it yet, I'll have a look this evening and let you know. Thanks

**Comment by EVODelavega** [comment]
@francesca64  Looks like that branch won't compile on Fedora. Probably because Fedora is using wayland, not X11. I'm getting the same errors on the hints.rs file (56 through 63), all basically look like this:

```
.cargo/git/checkouts/winit-610dc59f8cb53001/f1e450c/src/platform/linux/x11/util/hint.rs:56:13
   |
56 |             Desktop => b"_NET_WM_WINDOW_TYPE_DESKTOP\0",
   |             ^^^^^^^ help: consider using a reference: `&Desktop`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
```

**Comment by francesca64** [comment]
In Cargo.toml, change the glutin branch from `winit-git` to `winit-15` and then run `cargo update`. I accidentally broke the build on rustc<1.26.0, and it's fixed in a PR that isn't merged yet.

**Comment by EVODelavega** [comment]
@francesca64  Sorry, jumped the gun a little bit, used rustup to switch to nightly `rustc` (1.28), still had the same issue, but just quickly changed the hint.rs file to use references instead. Managed to compile with that, and everything is running peachy now. Dead keys are working mostly fine.

Edge cases like £ aren't working (ctrl+shift 3), but I can live with that as a compromise for now.

Thanks to everyone who looked into this issue

**Comment by zerinoid** [comment]
@francesca64 what happened to the branch? really need it for ubuntu
