### ISSUE TITLE
 cargo test --features="bench"    fails to build

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1161]
````
 cargo test --features="bench" 

   Compiling alacritty v0.1.0 (file:///home/matthias/alacritty)
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
    --> src/term/mod.rs:2103:33
     |
990  | /     pub fn renderable_cells<'b>(
991  | |         &'b self,
992  | |         config: &'b Config,
993  | |         selection: Option<&'b Selection>,
...    |
1012 | |         )
1013 | |     }
     | |_____- defined here
...
2103 |               let iter = terminal.renderable_cells(&config, None);
     |                                   ^^^^^^^^^^^^^^^^ expected 3 parameters

error: aborting due to previous error

````

@ f298ebb2179eff947cdb9cb7a4bd96e9739eac5c

**Comment by chrisduerr** [comment]
This actually must have been broken by https://github.com/jwilm/alacritty/commit/6eb634a2b83a8a401973ec9e52c7c7ffb5b9fe84, the benchmarks just aren't run a lot I guess :P.

I've opened a PR that fixes this here: #1162
